version: "3.9"
services:
  service-customer:
    image: quarkus/service-customer-jvm
    build: .
    ports:
      - "4545:4545"
    links:
      - mymongodb
    depends_on:
      - mymongodb

  mymongodb:
    image: mongo
    ports:
      - "27017:27017"